import type { DocumentType, ProcessData } from '../types';
import { createDriveFolder, findDriveFolderByName, type GoogleDriveFile } from './googleDriveService';

export interface DriveStructureManifest { root: GoogleDriveFile; folders: Record<string, GoogleDriveFile>; createdCount: number; existingCount: number; }
export const PORTAL_DRIVE_STRUCTURE = {
  system:'00_SISTEMA', models:'01_DOCUMENTOS', processes:'02_PROCESSOS', publicRepository:'03_REPOSITORIO_PUBLICO',
  modelChildren:['01_CARTA_CONVITE','02_ATA_DEFESA','03_TERMO_AUTORIZACAO','04_DECLARACAO_PARTICIPACAO'],
  processChildren:['00_MANIFESTO','00_FORMULARIOS','01_TRABALHO_COMPLETO','02_RESUMO_EXPANDIDO','03_CARTA_CONVITE','04_ATA_DEFESA','05_TERMO_AUTORIZACAO','06_DECLARACAO_COMISSAO','07_COMPROVANTES_ASTEN','08_PUBLICACAO'],
  processFormChildren:['01_CADASTRO_INICIAL','02_CONFIRMACAO_LOCAL','03_AVALIACAO','04_DADOS_FINAIS']
} as const;

export function extractGoogleDriveFolderId(input: string): string { const value=String(input||'').trim(); const match=value.match(/\/folders\/([a-zA-Z0-9_-]+)/)||value.match(/[?&]id=([a-zA-Z0-9_-]+)/); const id=match?.[1]||value; if(!/^[a-zA-Z0-9_-]{10,}$/.test(id)) throw new Error('ID de pasta do Google Drive inválido.'); return id; }
async function ensure(accessToken:string,name:string,parentId:string,appProperties?:Record<string,string>) { const existing=await findDriveFolderByName(accessToken,name,parentId); return existing?{file:existing,created:false}:{file:await createDriveFolder(accessToken,name,parentId,appProperties),created:true}; }

export async function bootstrapPortalDriveStructure(accessToken:string,rootInput:string):Promise<DriveStructureManifest>{
  const rootId=extractGoogleDriveFolderId(rootInput); const root={id:rootId,name:'PORTAL_TCC',mimeType:'application/vnd.google-apps.folder'}; const folders:Record<string,GoogleDriveFile>={}; let createdCount=0,existingCount=0;
  for(const [key,name] of Object.entries({system:PORTAL_DRIVE_STRUCTURE.system,models:PORTAL_DRIVE_STRUCTURE.models,processes:PORTAL_DRIVE_STRUCTURE.processes,publicRepository:PORTAL_DRIVE_STRUCTURE.publicRepository})){const r=await ensure(accessToken,name,rootId,{portal:'portal-tcc',schema:'4',section:key});folders[key]=r.file;r.created?createdCount++:existingCount++;}
  for(const name of PORTAL_DRIVE_STRUCTURE.modelChildren){const r=await ensure(accessToken,name,folders.models.id,{portal:'portal-tcc',type:'document'});folders[`models/${name}`]=r.file;r.created?createdCount++:existingCount++;for(const lifecycle of ['00_MODELO_ATIVO','01_HISTORICO_MODELOS','02_GERADOS','03_ASSINADOS']){const c=await ensure(accessToken,lifecycle,r.file.id,{portal:'portal-tcc',lifecycle});folders[`models/${name}/${lifecycle}`]=c.file;c.created?createdCount++:existingCount++;}}
  return {root,folders,createdCount,existingCount};
}

export async function ensureProcessDriveStructure(accessToken:string,processesRootId:string,process:Pick<ProcessData,'id'|'protocolo'>):Promise<DriveStructureManifest>{const year=process.protocolo.match(/(?:^|[^0-9])(20\d{2})(?:[^0-9]|$)/)?.[1]||String(new Date().getFullYear());const yr=await ensure(accessToken,year,processesRootId,{portal:'portal-tcc',year});const pr=await ensure(accessToken,process.protocolo,yr.file.id,{portal:'portal-tcc',processId:process.id,protocol:process.protocolo});const folders:Record<string,GoogleDriveFile>={year:yr.file,process:pr.file};let createdCount=Number(yr.created)+Number(pr.created),existingCount=Number(!yr.created)+Number(!pr.created);for(const name of PORTAL_DRIVE_STRUCTURE.processChildren){const r=await ensure(accessToken,name,pr.file.id,{portal:'portal-tcc',processId:process.id,section:name.slice(0,30)});folders[name]=r.file;r.created?createdCount++:existingCount++;}for(const name of PORTAL_DRIVE_STRUCTURE.processFormChildren){const r=await ensure(accessToken,name,folders['00_FORMULARIOS'].id,{portal:'portal-tcc',processId:process.id,formType:name});folders[`00_FORMULARIOS/${name}`]=r.file;r.created?createdCount++:existingCount++;}return{root:pr.file,folders,createdCount,existingCount};}

const LABEL:Record<DocumentType,string>={CONVITE:'CARTA_CONVITE',ATA:'ATA_DEFESA',TERMO:'TERMO_AUTORIZACAO',DECLARACAO:'DECLARACAO_PARTICIPACAO'};
export function buildPortalDriveFileName(input:{protocol:string;title?:string;studentNames?:string[];documentType:DocumentType|'TRABALHO_COMPLETO'|'RESUMO_EXPANDIDO'|'ASTEN_COMPROVANTE';version:number;lifecycle:'GERADO'|'ASSINADO';extension?:string}){const clean=(value:string,max:number)=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9]+/gi,'_').replace(/^_+|_+$/g,'').toUpperCase().slice(0,max),p=clean(input.protocol,40)||'TCC_SEM_CODIGO',students=(input.studentNames||[]).map(name=>clean(name.trim().split(/\s+/)[0],45)).filter(Boolean).join('_E_').slice(0,96),title=clean(input.title||'SEM_TITULO',80)||'SEM_TITULO',label=(LABEL as Record<string,string>)[input.documentType]||input.documentType,v=String(Math.max(1,Math.floor(input.version))).padStart(3,'0'),ext=String(input.extension||'pdf').replace(/[^a-z0-9]/gi,'').toLowerCase()||'pdf';return`${p}__${students?`${students}__`:''}${label}__v${v}__${input.lifecycle}.${ext}`;}
