import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib';
import type { buildAdvancedAnalytics } from './advancedAnalytics';
type Report=ReturnType<typeof buildAdvancedAnalytics>;
type Theme={primary:[number,number,number];accent:[number,number,number]};
const A4:[number,number]=[595.28,841.89],margin=52;
const clean=(value:unknown)=>String(value??'Não disponível').normalize('NFC').replace(/→/g,'->').replace(/[–—]/g,'-').replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/…/g,'...').replace(/•/g,'-').replace(/[^\u0020-\u00ff]/g,'?').replace(/[\u007f-\u009f]+/g,' ').replace(/\s+/g,' ').trim();
export function institutionalReportTheme(brand?:{primaryColor?:string;accentColor?:string}):Theme{
  const parse=(value:string|undefined,fallback:[number,number,number])=>{const match=String(value||'').match(/^#([0-9a-f]{6})$/i);return match?[0,2,4].map(index=>parseInt(match[1].slice(index,index+2),16)/255) as [number,number,number]:fallback;};
  return {primary:parse(brand?.primaryColor,[.02,.35,.25]),accent:parse(brand?.accentColor,[.04,.55,.4])};
}
function wrap(text:string,font:PDFFont,size:number,maxWidth:number){const words=clean(text).split(' '),lines:string[]=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(next,size)<=maxWidth)line=next;else{if(line)lines.push(line);line=word;}}if(line)lines.push(line);return lines;}
export async function buildInstitutionalReport(report:Report,profile:{courseName:string;institutionName:string},theme:Theme={primary:[.02,.35,.25],accent:[.04,.55,.4]}):Promise<Buffer>{
  const doc=await PDFDocument.create(),regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);
  const primary=rgb(...theme.primary),accent=rgb(...theme.accent),ink=rgb(.09,.12,.16),muted=rgb(.37,.41,.46),lineColor=rgb(.83,.86,.89);let page:PDFPage,y=0;
  const addPage=(chapter='Relatório institucional')=>{page=doc.addPage(A4);y=A4[1]-margin;page.drawText(clean(profile.institutionName),{x:margin,y,size:8,font:bold,color:primary});page.drawText(clean(chapter),{x:A4[0]-margin-bold.widthOfTextAtSize(clean(chapter),8),y,size:8,font:bold,color:muted});y-=28;};
  const ensure=(height:number,chapter?:string)=>{if(!page||y-height<margin+24)addPage(chapter);};
  const heading=(text:string,level=1)=>{const size=level===1?18:13;ensure(size+20,text);y-=4;page.drawText(clean(text),{x:margin,y,size,font:bold,color:level===1?primary:ink});y-=size+10;};
  const paragraph=(text:string,options:{bold?:boolean;color?:typeof ink;size?:number}={})=>{const font=options.bold?bold:regular,size=options.size||9.5;const lines=wrap(text,font,size,A4[0]-2*margin);ensure(lines.length*(size+4)+8);for(const item of lines){page.drawText(item,{x:margin,y,size,font,color:options.color||ink});y-=size+4;}y-=5;};
  const metric=(label:string,value:unknown,x:number,width:number)=>{page.drawRectangle({x,y:y-46,width,height:46,color:rgb(.95,.97,.96),borderColor:lineColor,borderWidth:1});page.drawText(clean(label),{x:x+10,y:y-17,size:7.5,font:bold,color:muted});page.drawText(clean(value),{x:x+10,y:y-37,size:16,font:bold,color:primary});};
  const table=(headers:string[],rows:unknown[][],widths:number[],chapter:string)=>{const rowHeight=22;ensure(rowHeight*2,chapter);let x=margin;for(let i=0;i<headers.length;i++){page.drawRectangle({x,y:y-rowHeight,width:widths[i],height:rowHeight,color:primary});page.drawText(headers[i],{x:x+5,y:y-14,size:7.2,font:bold,color:rgb(1,1,1)});x+=widths[i];}y-=rowHeight;for(const row of rows){ensure(rowHeight+2,chapter);x=margin;for(let i=0;i<headers.length;i++){page.drawRectangle({x,y:y-rowHeight,width:widths[i],height:rowHeight,borderColor:lineColor,borderWidth:.5});const value=clean(row[i]);page.drawText(value.length>34?value.slice(0,32)+'...':value,{x:x+5,y:y-14,size:7.2,font:regular,color:ink});x+=widths[i];}y-=rowHeight;}y-=12;};
  const chart=(title:string,entries:Array<{label:string;count:number;share:number}>,chapter:string)=>{heading(title,2);if(!entries.length){paragraph('Sem categorias publicáveis neste recorte.');return;}const top=entries.slice(0,8),barX=margin+155,barWidth=A4[0]-margin-barX;ensure(top.length*25+12,chapter);for(const item of top){const label=clean(item.label),value=Math.max(0,Math.min(100,Number(item.share)||0));page.drawText(label.length>26?label.slice(0,24)+'...':label,{x:margin,y:y-10,size:7.8,font:regular,color:ink});page.drawRectangle({x:barX,y:y-13,width:barWidth,height:11,color:rgb(.91,.93,.92)});page.drawRectangle({x:barX,y:y-13,width:barWidth*value/100,height:11,color:accent});page.drawText(`${item.count} (${value.toLocaleString('pt-BR')}%)`,{x:barX+4,y:y-11,size:6.6,font:bold,color:value>42?rgb(1,1,1):ink});y-=25;}y-=4;};
  addPage('Síntese executiva');heading('Panorama institucional dos TCCs');paragraph(`${profile.courseName} · Período: ${report.period==='TODOS'?'todos os períodos':report.period}`,{bold:true,size:12});paragraph(`Gerado em ${new Intl.DateTimeFormat('pt-BR',{dateStyle:'long',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(report.generatedAt))}.`,{color:muted});
  metric('TCCs',report.snapshot.totals.processes,margin,150);metric('Autores',report.snapshot.totals.authors,margin+164,150);metric('Conclusão',`${report.snapshot.rates.completion.toLocaleString('pt-BR')}%`,margin+328,150);y-=66;
  paragraph('Este relatório apresenta dados agregados do fluxo de TCC, sem nomes, e-mails, matrículas, títulos ou resumos. Categorias pequenas seguem a regra de supressão descrita na metodologia.');
  if(report.comparison)paragraph(`Comparação com ${report.compare}: ${report.comparison.count??'não disponível'} TCC(s), com ${report.comparison.completionRate??'não disponível'}% concluídos.`);
  heading('Perfil acadêmico');for(const [key,title] of [['areas','Áreas temáticas'],['themes','Temas principais'],['studyTypes','Tipos de estudo'],['purposes','Finalidades dos trabalhos']] as const)chart(title,report.snapshot.distributions[key].entries,'Perfil acadêmico');
  heading('Quantidade, situação e publicação');chart('Situação dos processos',report.snapshot.distributions.status.entries,'Quantidade e situação');chart('Resultados das defesas',report.snapshot.distributions.outcome.entries,'Quantidade e situação');chart('Tipos de trabalho',report.snapshot.distributions.workType.entries,'Quantidade e situação');
  heading('Evolução por período');table(['Período','TCCs','Conclusão'],report.trends.map(row=>[row.period,row.count??'N/D',row.completionRate===null?'N/D':`${row.completionRate}%`]),[180,130,180],'Evolução por período');
  heading('Tempos e gargalos do fluxo');table(['Etapa','Concluídas','Mediana','Em espera','Espera atual'],report.stages.map(row=>[row.label,row.completed??'N/D',row.medianDays===null?'N/D':`${row.medianDays} dias`,row.waiting??'N/D',row.medianWaitingDays===null?'N/D':`${row.medianWaitingDays} dias`]),[222,65,75,65,73],'Tempos do fluxo');paragraph('N/D significa que não há pelo menos três observações ou que a marcação histórica necessária não existe. N/D nunca deve ser interpretado como zero.');
  heading('Qualidade e cobertura dos dados');table(['Dimensão','Cobertura'],[['Área temática',`${report.snapshot.dataQuality.areaCoverage}%`],['Tema',`${report.snapshot.dataQuality.themeCoverage}%`],['Tipo de estudo',`${report.snapshot.dataQuality.studyTypeCoverage}%`],['Finalidade',`${report.snapshot.dataQuality.purposeCoverage}%`],['Palavras-chave',`${report.snapshot.dataQuality.keywordCoverage}%`]],[330,160],'Qualidade dos dados');
  heading('Metodologia, finalidade e limitações');paragraph('Unidade de contagem: um processo de TCC. O número de autores conta separadamente coautores. A conclusão depende do estado final do processo; a publicação representa a opção registrada pelo aluno e não substitui a assinatura do Termo de autorização.');paragraph(report.note);paragraph(report.snapshot.privacy.note);paragraph('Percentuais usam como denominador os TCCs do recorte selecionado. Medianas de tramitação usam apenas intervalos com datas válidas. Categorias não encontradas no catálogo publicado são classificadas como não informadas; grupos com menos de três ocorrências são agregados para reduzir risco de reidentificação.');
  for(const [index,current] of doc.getPages().entries()){const footer=`Portal de TCC · ${clean(report.period)} · página ${index+1} de ${doc.getPageCount()}`;current.drawLine({start:{x:margin,y:35},end:{x:A4[0]-margin,y:35},thickness:.5,color:lineColor});current.drawText(footer,{x:margin,y:20,size:7,font:regular,color:muted});}
  doc.setTitle(`Panorama institucional dos TCCs - ${report.period}`);doc.setSubject('Relatório estatístico agregado, sem dados pessoais');doc.setProducer('Portal Institucional de TCC');return Buffer.from(await doc.save({useObjectStreams:false}));
}
