import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,CheckCircle2,Clock3,RefreshCw,Send,Users}from'lucide-react';
import type{AstenIntegrationStatus,SignatureJob,SignatureJobStatus}from'../types';
import{apiClient}from'../services/apiClient';

const LABEL:Record<SignatureJobStatus,string>={WAITING_INTEGRATION:'Aguardando integração',QUEUED:'Na fila automática',READY_FOR_REVIEW:'Legado: revisão',APPROVED:'Legado: aprovado',SENDING:'Enviando',SENT:'Aguardando assinaturas',PARTIALLY_SIGNED:'Parcialmente assinado',SIGNED:'Assinado',DECLINED:'Recusado',EXPIRED:'Expirado',CANCELED:'Cancelado',PROVIDER_ERROR:'Falha recuperável',DRIVE_SYNC_PENDING:'Aguardando arquivo no Drive',ARCHIVED:'Arquivado'};
const retryable=(job:SignatureJob)=>job.providerCreationState!=='UNCERTAIN'&&['WAITING_INTEGRATION','QUEUED','PROVIDER_ERROR'].includes(job.status);

export const SignatureQueuePage:React.FC=()=>{
  const[jobs,setJobs]=useState<SignatureJob[]>([]),[status,setStatus]=useState<AstenIntegrationStatus|null>(null),[loading,setLoading]=useState(true),[working,setWorking]=useState(''),[message,setMessage]=useState('');
  const load=async()=>{setLoading(true);try{const[data,integration]=await Promise.all([apiClient.getSignatureJobs(),apiClient.getAstenStatus()]);setJobs(data);setStatus(integration);}catch(error){setMessage(error instanceof Error?error.message:'Falha ao abrir o acompanhamento.');}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const totals=useMemo(()=>({queued:jobs.filter(job=>job.providerCreationState!=='UNCERTAIN'&&['WAITING_INTEGRATION','QUEUED','SENDING'].includes(job.status)).length,pending:jobs.filter(job=>['SENT','PARTIALLY_SIGNED'].includes(job.status)).length,attention:jobs.filter(job=>job.providerCreationState==='UNCERTAIN').length,done:jobs.filter(job=>['SIGNED','DRIVE_SYNC_PENDING','ARCHIVED'].includes(job.status)).length}),[jobs]);
  const retry=async(job:SignatureJob)=>{setWorking(job.id);setMessage('');try{await apiClient.retrySignatureJob(job.id);setMessage(`${job.protocol}: reprocessamento concluído.`);await load();}catch(error){setMessage(error instanceof Error?error.message:'Falha ao reprocessar.');}finally{setWorking('');}};
  return <div className="space-y-4 p-4 sm:p-6">
    <header><h1 className="text-2xl font-black text-slate-950">Acompanhamento de assinaturas</h1><p className="mt-1 text-sm text-slate-600">Asten é a ferramenta exclusiva. Esta tela acompanha exceções; não existe aprovação manual antes do envio.</p></header>
    <section className={`rounded-2xl border p-4 ${status?.dispatchEnabled?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><div className="flex gap-3">{status?.dispatchEnabled?<CheckCircle2 className="h-5 w-5 text-emerald-700"/>:<AlertTriangle className="h-5 w-5 text-amber-700"/>}<div><strong>{status?.dispatchEnabled?'Asten conectada':'Asten ainda não conectada'}</strong><p className="mt-1 text-xs">{status?.securityMessage}</p></div></div></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Clock3/>} label="Em processamento" value={totals.queued}/><Metric icon={<Send/>} label="Em assinatura" value={totals.pending}/><Metric icon={<AlertTriangle/>} label="Exigem conferência" value={totals.attention}/><Metric icon={<CheckCircle2/>} label="Concluídos" value={totals.done}/></div>
    {message&&<p role="status" className="rounded-xl border border-slate-200 bg-white p-3 text-sm font-semibold">{message}</p>}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b p-4"><div><h2 className="font-black">Documentos e versões</h2><p className="text-sm text-slate-500">Carta-convite não entra na Asten. Termo: aluno(s) e orientador têm prioridade 1.</p></div><button onClick={load} className="min-h-11 min-w-11 rounded-lg border p-2" aria-label="Atualizar"><RefreshCw className="mx-auto h-4 w-4"/></button></div>{loading?<div className="p-10 text-center text-slate-500">Carregando…</div>:jobs.length===0?<div className="p-10 text-center text-slate-500">Nenhum documento gerado.</div>:<div className="divide-y">{jobs.map(job=><article key={job.id} className={`grid gap-4 p-4 lg:grid-cols-[1.2fr_1fr_auto] ${job.providerCreationState==='UNCERTAIN'?'bg-amber-50/70':''}`}><div><strong>{job.protocol} · {job.documentTitle}</strong><p className="text-sm text-slate-500">v{String(job.documentVersion).padStart(3,'0')} · {job.fileName}</p><p className="break-all font-mono text-xs text-slate-500">SHA-256 {job.contentSha256}</p>{job.providerCreationState==='UNCERTAIN'&&<div role="alert" className="mt-3 max-w-2xl rounded-lg border border-amber-300 bg-amber-100 p-3 text-sm text-amber-950"><strong className="block">Resultado ambíguo: reenvio automático bloqueado</strong><span>Confira este protocolo diretamente na conta Asten antes de qualquer intervenção. O portal não criará outro envelope enquanto o estado não for reconciliado.</span></div>}</div><div><div className="flex items-center gap-1 text-xs font-black uppercase text-slate-500"><Users className="h-4 w-4"/>Signatários</div>{job.signers.map(signer=><p key={signer.id} className="mt-1 text-sm"><strong>Prioridade {signer.signingOrder} · {signer.name}</strong><br/>{signer.email}</p>)}</div><div className="text-left lg:text-right"><span className={`inline-flex rounded-full border px-2 py-1 text-xs font-black uppercase ${job.providerCreationState==='UNCERTAIN'?'border-amber-300 bg-amber-100 text-amber-950':'border-slate-200 bg-slate-50'}`}>{job.providerCreationState==='UNCERTAIN'?'Conferência obrigatória':LABEL[job.status]}</span>{retryable(job)&&<button onClick={()=>retry(job)} disabled={working===job.id} className="mt-2 min-h-11 rounded-lg bg-slate-900 px-3 py-2 text-xs font-black text-white disabled:opacity-50 lg:ml-auto lg:block">Reprocessar</button>}{job.driveSignedWebViewLink&&<a href={job.driveSignedWebViewLink} target="_blank" rel="noreferrer" className="mt-2 block text-sm font-bold text-blue-700 underline">Abrir no Drive</a>}{job.lastError&&<p className="mt-2 max-w-xs text-sm text-red-700">{job.lastError}</p>}</div></article>)}</div>}</section>
  </div>;
};

const Metric:React.FC<{icon:React.ReactElement;label:string;value:number}>=({icon,label,value})=><div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2 text-slate-500">{React.cloneElement(icon,{className:'h-4 w-4'})}<span className="text-xs font-black uppercase">{label}</span></div><div className="mt-2 text-2xl font-black">{value}</div></div>;
