import React, { useEffect, useState } from 'react';
import { CheckCircle2, FileCheck2, Loader2, ShieldCheck, XCircle } from 'lucide-react';
import { apiClient } from '../services/apiClient';

export const VerificationPage:React.FC<{code:string}>=({code})=>{
  const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[result,setResult]=useState<any>(null),[error,setError]=useState('');
  useEffect(()=>{void apiClient.getPublicVerification(code).then(setData).catch(error=>setError(error instanceof Error?error.message:'Documento não encontrado.')).finally(()=>setLoading(false));},[code]);
  const verifyFile=async(file?:File)=>{if(!file)return;setError('');setResult(null);if(file.type!=='application/pdf'||file.size<=0||file.size>50*1024*1024){setError('Selecione um PDF válido de até 50 MB.');return;}try{setResult(await apiClient.checkVerificationPdfFile(code,file));}catch(error){setError(error instanceof Error?error.message:'Falha ao validar o arquivo.');}};
  if(loading)return <main className="grid min-h-screen place-items-center bg-slate-100"><div className="flex items-center gap-2 text-sm font-bold text-slate-600"><Loader2 className="h-5 w-5 animate-spin"/>Validando registro…</div></main>;
  return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><section className="mx-auto max-w-2xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl"><div className={`p-6 text-white ${data?.valid?'bg-emerald-800':'bg-slate-800'}`}><div className="flex items-center gap-3"><ShieldCheck className="h-8 w-8"/><div><p className="text-xs font-black uppercase tracking-wider">Validação institucional</p><h1 className="mt-1 text-2xl font-black">{data?.valid?'Documento autêntico':'Registro não localizado'}</h1></div></div></div><div className="grid gap-6 p-6 sm:grid-cols-[1fr_auto]">{data?.valid?<><div className="space-y-3"><p className="text-sm text-slate-600">Este registro confirma que o PDF assinado foi arquivado pelo portal. A consulta pública não exibe nomes, e-mails ou matrículas.</p>{[['Instituição',data.institution],['Curso',data.course],['Protocolo',data.protocol],['Documento',data.documentType],['Versão',data.version],['Arquivado em',new Date(data.signedAt).toLocaleString('pt-BR')]].map(([label,value])=><div key={String(label)} className="border-b pb-2"><span className="block text-[10px] font-black uppercase text-slate-500">{label}</span><strong className="text-sm text-slate-950">{value}</strong></div>)}<div><span className="block text-[10px] font-black uppercase text-slate-500">SHA-256</span><code className="mt-1 block break-all rounded-lg bg-slate-100 p-2 text-[10px]">{data.sha256}</code></div></div><img src={`/api/public/verification/${encodeURIComponent(code)}/qr.svg`} alt="QR Code desta validação" className="h-48 w-48 rounded-xl border bg-white p-2"/></>:<p className="text-sm text-slate-600">Confira o endereço ou solicite o documento novamente à instituição.</p>}</div>{data?.valid&&<div className="border-t bg-slate-50 p-6"><div className="flex items-center gap-2"><FileCheck2 className="h-5 w-5 text-blue-700"/><h2 className="font-black">Conferir um PDF</h2></div><p className="mt-1 text-xs text-slate-600">O arquivo é processado apenas para calcular o hash e não fica armazenado.</p><label className="mt-3 inline-flex cursor-pointer rounded-xl bg-blue-800 px-4 py-2.5 text-xs font-black text-white">Selecionar PDF<input className="sr-only" type="file" accept="application/pdf,.pdf" onChange={event=>void verifyFile(event.target.files?.[0])}/></label>{result&&<div className={`mt-3 flex items-center gap-2 rounded-xl border p-3 text-sm font-bold ${result.valid?'border-emerald-200 bg-emerald-50 text-emerald-900':'border-red-200 bg-red-50 text-red-900'}`}>{result.valid?<CheckCircle2 className="h-5 w-5"/>:<XCircle className="h-5 w-5"/>}{result.valid?'O PDF corresponde exatamente ao documento arquivado.':'O PDF não corresponde ao registro.'}</div>}{error&&<p className="mt-3 text-sm font-semibold text-red-700">{error}</p>}</div>}</section></main>;
};
