import React, { useEffect, useState } from 'react';
import { apiClient } from '../services/apiClient';
const distributionNames: Record<string,string> = { status:'Situação dos processos', outcome:'Resultados da defesa', workType:'Tipo de trabalho', defenseFormat:'Formato da defesa', themes:'Temas principais', areas:'Áreas temáticas', studyTypes:'Tipos de estudo', purposes:'Finalidades', keywords:'Palavras-chave' };
export function AdvancedAnalyticsPanel({ refreshKey }: { refreshKey?: string }) {
  const [data,setData]=useState<any>(null);
  const [period,setPeriod]=useState('');
  const [compare,setCompare]=useState('');
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(true);
  useEffect(()=>{ let cancelled=false;setBusy(true);apiClient.getAdvancedAnalytics(period,compare).then(result=>{if(!cancelled){setData(result);setError('');}}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[period,compare,refreshKey]);
  const download=async(format:'csv'|'pdf')=>{setBusy(true);try{const file=await apiClient.downloadAdvancedAnalytics(format,period,compare);const url=URL.createObjectURL(file.blob);const a=document.createElement('a');a.href=url;a.download=file.fileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Falha ao exportar.');}finally{setBusy(false);}};
  const number=(value:number|null|undefined)=>value===null||value===undefined?'Não disponível':new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(value);
  return <section aria-labelledby="advanced-analytics-title" className="portal-workspace portal-card space-y-5 p-5">
    <header><h3 id="advanced-analytics-title" className="text-xl font-bold">Panorama dos TCCs</h3><p className="mt-2">Áreas, temas, métodos e finalidades do catálogo do Master, comparados por período e acompanhados dos tempos de tramitação.</p></header>
    <div className="grid items-end gap-3 sm:grid-cols-2 lg:grid-cols-4"><label>Período<select className="portal-input" value={period} onChange={e=>setPeriod(e.target.value)}><option value="">Todos os períodos</option>{data?.periods.map((p:string)=><option key={p}>{p}</option>)}</select></label><label>Comparar com<select className="portal-input" value={compare} onChange={e=>setCompare(e.target.value)}><option value="">Sem comparação</option>{data?.periods.map((p:string)=><option key={p}>{p}</option>)}</select></label><button type="button" className="portal-action" disabled={busy} onClick={()=>void download('csv')}>Exportar CSV</button><button type="button" className="portal-action" disabled={busy} onClick={()=>void download('pdf')}>Exportar PDF</button></div>
    {error&&<p role="alert">{error}</p>}{busy&&<p role="status">Preparando indicadores…</p>}
    {data&&<><div className="grid gap-3 sm:grid-cols-3">{[['TCCs cadastrados',data.snapshot.totals.processes],['Conclusão (%)',data.snapshot.rates.completion],['Autores',data.snapshot.totals.authors]].map(([label,value])=><div className="portal-card p-4" key={label}><p className="text-sm">{label}</p><strong className="text-3xl">{number(value)}</strong></div>)}</div>
      <p className="text-sm">{data.note} Categorias fora do catálogo são apresentadas como não classificadas. Publicação significa solicitação do aluno; não representa autorização ainda em assinatura.</p>
      {data.comparison&&<p className="portal-card p-4">Comparação · {compare}: {number(data.comparison.count)} TCCs e {number(data.comparison.completionRate)}% concluídos.</p>}
      <div className="grid gap-4 xl:grid-cols-2">{Object.entries(data.snapshot.distributions).map(([key,raw])=>{const d=raw as any;return <figure key={key} className="portal-card p-4"><figcaption className="mb-3 font-bold">{distributionNames[key]||key}</figcaption><ul className="space-y-3">{d.entries.map((entry:any)=><li key={entry.label}><div className="flex justify-between gap-3 text-sm"><span>{entry.label}</span><strong>{entry.count} · {number(entry.share)}%</strong></div><meter className="portal-stat-meter" min={0} max={100} value={Math.min(100,entry.share)} aria-label={`${entry.label}: ${entry.count} TCCs, ${entry.share}%`}/></li>)}</ul>{!d.entries.length&&<p className="text-sm">Sem categorias com volume suficiente.</p>}<p className="mt-3 text-sm">Não classificado: {d.unknown}. Ocorrências agrupadas por privacidade: {d.suppressed}.</p></figure>;})}</div>
      <div className="overflow-x-auto"><table className="portal-data-table"><caption className="mb-2 text-left font-bold">Evolução por período acadêmico</caption><thead><tr><th scope="col">Período</th><th scope="col">TCCs</th><th scope="col">Concluídos (%)</th></tr></thead><tbody>{data.trends.map((row:any)=><tr key={row.period}><th scope="row">{row.period}</th><td>{number(row.count)}</td><td>{number(row.completionRate)}</td></tr>)}</tbody></table></div>
      <div className="overflow-x-auto"><table className="portal-data-table"><caption className="mb-2 text-left font-bold">Onde o processo aguarda · medianas em dias</caption><thead><tr><th scope="col">Etapa</th><th scope="col">Concluídas</th><th scope="col">Mediana</th><th scope="col">Em espera</th><th scope="col">Espera atual</th></tr></thead><tbody>{data.stages.map((row:any)=><tr key={row.label}><th scope="row">{row.label}</th><td>{number(row.completed)}</td><td>{number(row.medianDays)}</td><td>{number(row.waiting)}</td><td>{number(row.medianWaitingDays)}</td></tr>)}</tbody></table></div>
      <details><summary className="cursor-pointer font-bold">Tempo de execução das ações (segundos)</summary><ul className="mt-3 space-y-2">{data.actions.map((row:any)=><li key={row.label}>{row.label}: {number(row.medianSeconds)} s · {number(row.count)} execuções</li>)}</ul></details>
    </>}
  </section>;
}
