import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,CheckCircle2,Loader2,Mail,RefreshCw,Workflow}from'lucide-react';
import{apiClient}from'../services/apiClient';

export const OperationsMonitorPanel:React.FC=()=>{
  const[deliveries,setDeliveries]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[archives,setArchives]=useState<any[]>([]),[asten,setAsten]=useState<any>(null),[working,setWorking]=useState(''),[message,setMessage]=useState('');
  const load=async()=>{setWorking('load');try{const[emailRows,workflowRows,archiveRows,astenRows]=await Promise.all([apiClient.getEmailDeliveries(),apiClient.getWorkflowRuns(),apiClient.getFormArchives(),apiClient.getAstenDashboard()]);setDeliveries(emailRows);setRuns(workflowRows);setArchives(archiveRows);setAsten(astenRows);setMessage('');}catch(error){setMessage(error instanceof Error?error.message:'Falha ao consultar a operação.');}finally{setWorking('');}};
  useEffect(()=>{void load();},[]);
  const emailFailures=useMemo(()=>deliveries.filter(item=>item.status!=='ACCEPTED_BY_GMAIL'),[deliveries]);
  const workflowFailures=useMemo(()=>runs.filter(item=>item.status!=='COMPLETED'),[runs]);
  const archiveFailures=useMemo(()=>archives.filter(item=>item.status==='FAILED'),[archives]);
  const retry=async(id:string)=>{setWorking(id);try{await apiClient.retryEmailDelivery(id);await load();}catch(error){setMessage(error instanceof Error?error.message:'Falha na nova tentativa.');}finally{setWorking('');}};
  const retryArchive=async(id:string)=>{setWorking(id);try{await apiClient.retryFormArchive(id);await load();}catch(error){setMessage(error instanceof Error?error.message:'Falha ao arquivar o formulário.');}finally{setWorking('');}};
  const cards=[{label:'E-mails aceitos pelo Gmail',value:deliveries.length-emailFailures.length,total:deliveries.length,ok:emailFailures.length===0,icon:Mail},{label:'Execuções do fluxo',value:runs.length-workflowFailures.length,total:runs.length,ok:workflowFailures.length===0,icon:Workflow},{label:'Formulários no Drive',value:archives.length-archiveFailures.length,total:archives.length,ok:archiveFailures.length===0,icon:CheckCircle2},{label:'Asten requer atenção',value:asten?.needsAttention?.length||0,total:asten?.totalJobs||0,ok:!(asten?.needsAttention?.length),icon:AlertTriangle}];
  return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm" aria-label="Monitor operacional"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-black text-slate-950">Monitor operacional</h3><p className="mt-1 text-xs text-slate-600">Confirma aceite do Gmail, execução do fluxo, arquivamento no Drive e eventos Asten. Aceite do Gmail não equivale à leitura pelo destinatário.</p></div><button type="button" onClick={()=>void load()} disabled={Boolean(working)} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-slate-50 px-3 py-2 text-xs font-black disabled:opacity-40">{working==='load'?<Loader2 className="h-4 w-4 animate-spin"/>:<RefreshCw className="h-4 w-4"/>}Atualizar</button></div>{message&&<p role="alert" className="mt-3 rounded-lg border border-red-200 bg-red-50 p-2 text-xs text-red-900">{message}</p>}<div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{cards.map(card=>{const Icon=card.icon;return <article key={card.label} className={`rounded-xl border p-3 ${card.ok?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><Icon className={`h-4 w-4 ${card.ok?'text-emerald-700':'text-amber-700'}`}/><strong className="mt-2 block text-lg text-slate-950">{card.value}/{card.total}</strong><span className="text-[11px] font-semibold text-slate-600">{card.label}</span></article>;})}</div>{emailFailures.length>0&&<div className="mt-4"><h4 className="text-xs font-black uppercase text-slate-800">E-mails pendentes ou com falha</h4><div className="mt-2 space-y-2">{emailFailures.slice(0,8).map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-amber-200 bg-amber-50 p-2 text-xs"><span><strong>{item.subject}</strong> · {item.recipient} · {item.status}</span><button type="button" onClick={()=>void retry(item.id)} disabled={Boolean(working)} className="rounded-md bg-slate-900 px-2.5 py-1.5 font-black text-white disabled:opacity-40">{working===item.id?'Tentando…':'Tentar novamente'}</button></div>)}</div></div>}{archiveFailures.length>0&&<div className="mt-4"><h4 className="text-xs font-black uppercase text-slate-800">Formulários aguardando Drive</h4><div className="mt-2 space-y-2">{archiveFailures.slice(0,8).map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-amber-200 bg-amber-50 p-2 text-xs"><span><strong>{item.formType}</strong> · {item.lastError||'Falha no arquivamento'}</span><button type="button" onClick={()=>void retryArchive(item.id)} disabled={Boolean(working)} className="rounded-md bg-slate-900 px-2.5 py-1.5 font-black text-white disabled:opacity-40">{working===item.id?'Arquivando…':'Arquivar novamente'}</button></div>)}</div></div>}</section>;
};
