import React, { useState } from 'react';
import type { IntegrationStudioSettings } from '../types/integrationStudio';
import type { CatalogEntry, OperationalConfig, VariablePresentation } from '../types/operationalConfig';
import { formatVariable, registrationQuestions } from '../utils/operationalConfig';
import { variableLineage } from '../utils/variableLineage';
import { apiClient } from '../services/apiClient';
import { WorkflowWorkbenchPanel } from './WorkflowWorkbenchPanel';
const labels = { AREA_TEMATICA: 'Área temática', TEMA_PRINCIPAL: 'Tema', TIPO_DE_ESTUDO: 'Tipo de estudo', FINALIDADE_DO_TRABALHO: 'Finalidade' };
const formats = { original: 'Original', date: 'Data numérica', date_long: 'Data por extenso', time: 'Hora numérica', time_long: 'Hora por extenso', datetime: 'Data e hora numéricas', datetime_long: 'Data e hora por extenso' };
export function OperationalDesignerPanel({ studio, config, onChange, onInitialForm }: { studio: IntegrationStudioSettings; config: OperationalConfig; onChange: (value: OperationalConfig)=>void; onInitialForm: (questions: any[])=>void }) {
  const [artifact, setArtifact] = useState('tmpl-convite');
  const [simulation, setSimulation] = useState<any>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [publication, setPublication] = useState(true);
  const [secondAuthor, setSecondAuthor] = useState(false);
  const [locationConfirmed, setLocationConfirmed] = useState(true);
  const [failActionId, setFailActionId] = useState('');
  const [mobile, setMobile] = useState(false);
  const [dark, setDark] = useState(false);
  const [search, setSearch] = useState('');
  const rules = config.presentations[artifact] || [];
  const lineage = variableLineage(studio);
  const changeRules = (value: VariablePresentation[]) => onChange({ ...config, presentations: { ...config.presentations, [artifact]: value } });
  const catalogChange = (id: string, update: Partial<CatalogEntry>) => onChange({ ...config, catalogs: config.catalogs.map(e=>e.id===id?{...e,...update}:e) });
  const run = async () => { setBusy(true); setError(''); try { setSimulation(await apiClient.simulateWorkflow(studio,{publication,secondAuthor,locationConfirmed,failActionId})); } catch(e) {setError(e instanceof Error?e.message:'Falha na simulação.');} finally {setBusy(false);} };
  return <section className="portal-workspace space-y-5" aria-label="Oficina operacional">
    <header className="portal-card p-5"><h3 className="text-xl font-bold">Oficina da secretaria</h3><p className="mt-2 leading-6">Prepare o cadastro, teste a sequência e confira como cada variável aparece nos documentos e e-mails. As alterações entram em uso ao publicar o Estúdio.</p></header>
    <details open className="portal-card p-5"><summary className="cursor-pointer text-lg font-semibold">1. Cadastro e pedido de reserva</summary><div className="mt-4 grid gap-4 md:grid-cols-2">
      <label>E-mail do departamento<input className="portal-input mt-2" type="email" value={config.reservation.departmentEmail} onChange={e=>onChange({...config,reservation:{...config.reservation,departmentEmail:e.target.value}})}/></label>
      <label>Locais disponíveis (um por linha)<textarea rows={3} className="portal-input mt-2" value={config.reservation.locations.join('\n')} onChange={e=>onChange({...config,reservation:{...config.reservation,locations:e.target.value.split('\n')}})}/></label>
    </div><p className="my-3 text-sm">Edite perguntas, seções e instruções na aba Formulários. Os campos essenciais de autoria e assinatura são preservados. Campos adicionais alimentam os modelos e relatórios.</p><button className="portal-action" type="button" onClick={()=>onInitialForm(registrationQuestions(studio).map(q=>({...q,expectedAnswer:q.helpText||''})))}>Atualizar o editor com os campos do cadastro real</button></details>
    <details className="portal-card p-5"><summary className="cursor-pointer text-lg font-semibold">2. Catálogo de áreas, temas e métodos</summary><p className="my-3 text-sm">Sinônimos convergem para a categoria oficial. Datas de vigência controlam as opções oferecidas; os relatórios preservam a classificação histórica.</p>
      <div className="space-y-3">{config.catalogs.map(entry=><article className="portal-card grid gap-3 p-3 md:grid-cols-3" key={entry.id}>
        <label>Categoria<select className="portal-input" value={entry.kind} onChange={e=>catalogChange(entry.id,{kind:e.target.value as CatalogEntry['kind']})}>{Object.entries(labels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
        <label>Nome oficial<input className="portal-input" value={entry.label} onChange={e=>catalogChange(entry.id,{label:e.target.value})}/></label><label>Sinônimos (separados por ;)<input className="portal-input" value={entry.aliases.join(';')} onChange={e=>catalogChange(entry.id,{aliases:e.target.value.split(';')})}/></label>
        <label>Válido a partir de<input type="date" className="portal-input" value={entry.validFrom||''} onChange={e=>catalogChange(entry.id,{validFrom:e.target.value})}/></label><label>Válido até<input type="date" className="portal-input" value={entry.validUntil||''} onChange={e=>catalogChange(entry.id,{validUntil:e.target.value})}/></label><label className="flex items-center gap-2"><input type="checkbox" checked={entry.active} onChange={e=>catalogChange(entry.id,{active:e.target.checked})}/>Disponível para novos cadastros</label>
      </article>)}</div><button className="portal-action mt-3" type="button" onClick={()=>onChange({...config,catalogs:[...config.catalogs,{id:crypto.randomUUID(),kind:'AREA_TEMATICA',label:'',aliases:[],active:true}]})}>Adicionar categoria</button>
    </details>
    <details className="portal-card p-5"><summary className="cursor-pointer text-lg font-semibold">3. Formatação dos marcadores</summary><p className="my-3 text-sm">Use marcadores diferentes para apresentar a mesma origem em formatos diferentes. A formatação do arquivo do Master é preservada; o negrito se aplica apenas ao marcador selecionado.</p>
      <label>Documento ou e-mail<select className="portal-input my-2" value={artifact} onChange={e=>setArtifact(e.target.value)}>{[...studio.docTemplates,...studio.emailTemplates].map(a=><option key={String(a.id)} value={String(a.id)}>{String(a.label||a.name||a.id)}</option>)}</select></label>
      <div className="mb-3 flex flex-wrap gap-2">{((studio.docTemplates.find(d=>d.id===artifact)?.variables||[]) as string[]).map(marker=><button type="button" className="portal-action" key={marker} onClick={()=>changeRules([...rules,{marker:marker.replace(/^<<|>>$|^\{\{|\}\}$/g,''),source:'TITULO',format:'original',letterCase:'original',bold:false}])}>{marker}</button>)}</div>
      {rules.map((rule,i)=><article key={i} className="portal-card mb-3 grid gap-3 p-3 sm:grid-cols-2 lg:grid-cols-3">
        <label>Marcador no modelo<input className="portal-input" value={rule.marker} onChange={e=>changeRules(rules.map((r,n)=>n===i?{...r,marker:e.target.value}:r))}/></label><label>Variável de origem<input list="lineage-keys" className="portal-input" value={rule.source} onChange={e=>changeRules(rules.map((r,n)=>n===i?{...r,source:e.target.value.toUpperCase()}:r))}/></label>
        <label>Formato<select className="portal-input" value={rule.format} onChange={e=>changeRules(rules.map((r,n)=>n===i?{...r,format:e.target.value as VariablePresentation['format']}:r))}>{Object.entries(formats).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
        <label>Maiúsculas e minúsculas<select className="portal-input" value={rule.letterCase} onChange={e=>changeRules(rules.map((r,n)=>n===i?{...r,letterCase:e.target.value as VariablePresentation['letterCase']}:r))}><option value="original">Como preenchido</option><option value="upper">CAIXA ALTA</option><option value="lower">caixa baixa</option></select></label><label className="flex items-center gap-2"><input type="checkbox" checked={rule.bold} onChange={e=>changeRules(rules.map((r,n)=>n===i?{...r,bold:e.target.checked}:r))}/>Negrito no documento</label><button type="button" className="portal-action" onClick={()=>changeRules(rules.filter((_,n)=>n!==i))}>Remover marcador</button>
        <p className="sm:col-span-2 lg:col-span-3 text-sm">Exemplo: <span style={{fontWeight:rule.bold?700:400}}>{formatVariable(rule.format==='original'?'Exemplo de conteúdo':'2026-09-08T17:30:00Z',rule,studio.operationsPolicy?.timezone)}</span></p>
      </article>)}<datalist id="lineage-keys">{lineage.map(r=><option key={r.key}>{r.key}</option>)}</datalist><button className="portal-action" type="button" onClick={()=>changeRules([...rules,{marker:'DATA_CONVITE',source:'DEFESA_DATA_HORA',format:'datetime_long',letterCase:'original',bold:false}])}>Adicionar apresentação de variável</button>
    </details>
    <details className="portal-card p-5"><summary className="cursor-pointer text-lg font-semibold">4. Mapa de origem e utilização das variáveis</summary><label className="mt-4 block">Buscar variável<input className="portal-input" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="mt-4 overflow-x-auto"><table className="portal-data-table"><caption className="sr-only">Linhagem de variáveis, origens e destinos</caption><thead><tr><th scope="col">Variável</th><th scope="col">Onde nasce</th><th scope="col">Onde é utilizada</th></tr></thead><tbody>{lineage.filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase())).map(r=><tr key={r.key}><th scope="row">{r.key}</th><td>{r.origins.join('; ')||'Dados do processo ou configuração institucional'}</td><td>{r.uses.join('; ')||'Sem uso identificado no pacote atual'}</td></tr>)}</tbody></table></div></details>
    <details className="portal-card p-5"><summary className="cursor-pointer text-lg font-semibold">5. Critérios para sugerir melhorias</summary><div className="mt-4 grid gap-4 md:grid-cols-3"><label>Dias sem movimentação<input type="number" min={1} max={365} className="portal-input" value={config.diagnostics.staleDays} onChange={e=>onChange({...config,diagnostics:{...config.diagnostics,staleDays:Number(e.target.value)}})}/></label><label>Cobertura mínima dos dados (%)<input type="number" min={1} max={100} className="portal-input" value={config.diagnostics.minimumCoverage} onChange={e=>onChange({...config,diagnostics:{...config.diagnostics,minimumCoverage:Number(e.target.value)}})}/></label><label>Prioridade da recomendação<select className="portal-input" value={config.diagnostics.priority} onChange={e=>onChange({...config,diagnostics:{...config.diagnostics,priority:e.target.value as 'P1'|'P2'|'P3'}})}><option value="P1">Alta</option><option value="P2">Normal</option><option value="P3">Planejada</option></select></label></div><p className="mt-3 text-sm">Falhas de integração mantêm prioridade alta. Os dois arquivos vivos registram evidências e decisões; mudanças operacionais continuam sendo publicadas pelo Master.</p></details>
    <details open className="portal-card p-5"><summary className="cursor-pointer text-lg font-semibold">6. Simular o percurso e conferir e-mails</summary><div className="my-4 flex flex-wrap gap-4">{[[publication,setPublication,'Autoriza publicação'],[secondAuthor,setSecondAuthor,'Dois autores'],[locationConfirmed,setLocationConfirmed,'Departamento confirmou o local']].map(([value,setter,label])=><label key={String(label)} className="flex items-center gap-2"><input type="checkbox" checked={Boolean(value)} onChange={e=>(setter as (v:boolean)=>void)(e.target.checked)}/>{String(label)}</label>)}</div>
      <label>Ensaio de falha em documento<select className="portal-input mb-3" value={failActionId} onChange={e=>setFailActionId(e.target.value)}><option value="">Nenhuma falha simulada</option>{studio.workflowStages.flatMap(s=>((s.actions||[]) as any[]).filter(a=>a.type==='doc'||a.kind==='DOCUMENT').map(a=><option key={a.id} value={a.id}>{String(s.title)} · {a.title}</option>))}</select></label>
      <button className="portal-action portal-action-primary" type="button" disabled={busy} onClick={()=>void run()}>{busy?'Executando cenário…':'Simular configuração atual'}</button>
      {error&&<p role="alert" className="my-3 text-red-800">{error}</p>}
      {simulation&&<div className="mt-4 space-y-4"><p role="status" className="rounded-lg border p-3">{simulation.note}</p><ol className="space-y-3">{simulation.events.map((event:any,i:number)=><li key={i} className="portal-card border-l-4 p-3"><p className="font-semibold">{i+1}. {event.role}</p><p className="text-sm">{event.event} · {event.state}</p>{Array.isArray(event.details)&&<ul className="mt-2 space-y-1 text-sm">{event.details.map((a:any)=><li key={a.actionId}>{a.kind}: {a.status}{a.error?` — ${a.error}`:''}</li>)}</ul>}</li>)}</ol>
      <div className="flex gap-4"><label><input type="checkbox" checked={mobile} onChange={e=>setMobile(e.target.checked)}/> Prévia de celular</label><label><input type="checkbox" checked={dark} onChange={e=>setDark(e.target.checked)}/> Fundo escuro</label></div>
      {simulation.emails.map((mail:any,i:number)=><article key={i} className="portal-card p-4"><h4 className="font-bold">{mail.subject}</h4><p className="my-2 text-sm break-all">Destinatários calculados: {mail.to.join('; ')}<br/>Anexos previstos: {mail.attachments.join(', ')||'Nenhum'}</p><iframe title={`Prévia isolada do e-mail ${i+1}`} sandbox="" className="mx-auto block h-80 max-w-full rounded-lg border" style={{width:mobile?360:720}} srcDoc={`<html><head><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:16px/1.6 Arial;padding:20px;overflow-wrap:anywhere;background:${dark?'#111827':'#ffffff'};color:${dark?'#ffffff':'#111827'}}pre{white-space:pre-wrap;font:inherit}</style></head><body>${mail.html||'<pre>'+String(mail.text).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')+'</pre>'}</body></html>`}/></article>)}
      <p className="text-sm">Homologação real: execute o roteiro em docs/HOMOLOGACAO_RC8.md após conectar as contas. Uma prévia não comprova entrega pelo Gmail, conversão fiel do modelo ou assinatura pela Asten.</p></div>}
    </details>
    <WorkflowWorkbenchPanel studio={studio} config={config} onChange={onChange}/>
  </section>;
}
