import React, { useEffect, useState } from 'react';
import { BarChart3, CalendarDays, CheckCircle2, Flag, Loader2, Save, ShieldCheck } from 'lucide-react';
import { apiClient } from '../services/apiClient';
import type { AcademicCycle, InstallationProfile, PortalFeatureFlag } from '../types';
import { DEFAULT_INSTALLATION_PROFILE } from '../constants/installation';

const fieldClass='w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100';
const card='rounded-2xl border border-slate-200 bg-white p-4 shadow-sm';

export const PortalGovernancePanel:React.FC=()=>{
  const[profile,setProfile]=useState<InstallationProfile>(DEFAULT_INSTALLATION_PROFILE),[revision,setRevision]=useState(''),[cycles,setCycles]=useState<AcademicCycle[]>([]),[flags,setFlags]=useState<PortalFeatureFlag[]>([]),[metrics,setMetrics]=useState<any>(null),[transfers,setTransfers]=useState<any[]>([]),[message,setMessage]=useState(''),[working,setWorking]=useState('');
  const[newCycle,setNewCycle]=useState({label:'',year:new Date().getFullYear(),term:'1',submissionOpenAt:'',submissionCloseAt:'',defenseStartAt:'',defenseEndAt:''});
  const[transfer,setTransfer]=useState({role:'COMMISSION_PRESIDENT' as 'MASTER_ADMIN'|'COMMISSION_PRESIDENT',targetEmail:''});
  const load=async()=>{const results=await Promise.allSettled([apiClient.getInstallationProfile(),apiClient.getAcademicCycles(),apiClient.getFeatureFlags(),apiClient.getAdminMetrics(),apiClient.getAdministrationTransfers()]);if(results[0].status==='fulfilled'){setProfile(results[0].value.profile);setRevision(results[0].value.updatedAt);}if(results[1].status==='fulfilled')setCycles(results[1].value);if(results[2].status==='fulfilled')setFlags(results[2].value);if(results[3].status==='fulfilled')setMetrics(results[3].value);if(results[4].status==='fulfilled')setTransfers(results[4].value);};
  useEffect(()=>{void load();},[]);
  const saveProfile=async()=>{setWorking('profile');setMessage('');try{const result=await apiClient.updateInstallationProfile(profile,revision);setProfile(result.profile);setRevision(result.updatedAt);setMessage('Identidade da instalação publicada para todo o portal.');}catch(error){setMessage(error instanceof Error?error.message:'Falha ao salvar.');}finally{setWorking('');}};
  const createCycle=async(event:React.FormEvent)=>{event.preventDefault();setWorking('cycle');try{await apiClient.createAcademicCycle(newCycle);setNewCycle({...newCycle,label:'',submissionOpenAt:'',submissionCloseAt:'',defenseStartAt:'',defenseEndAt:''});await load();setMessage('Período criado em rascunho. Abra-o quando as inscrições puderem começar.');}catch(error){setMessage(error instanceof Error?error.message:'Falha ao criar período.');}finally{setWorking('');}};
  const setCycleStatus=async(cycle:AcademicCycle,status:AcademicCycle['status'])=>{setWorking(cycle.id);try{await apiClient.updateAcademicCycle(cycle.id,{status});await load();}catch(error){setMessage(error instanceof Error?error.message:'Falha ao alterar período.');}finally{setWorking('');}};
  const toggleFlag=async(flag:PortalFeatureFlag)=>{setWorking(flag.key);try{await apiClient.updateFeatureFlag(flag.key,{enabled:!flag.enabled,audience:flag.audience});await load();}catch(error){setMessage(error instanceof Error?error.message:'Falha ao alterar funcionalidade.');}finally{setWorking('');}};
  const startTransfer=async(event:React.FormEvent)=>{event.preventDefault();setWorking('transfer');try{await apiClient.createAdministrationTransfer(transfer.role,transfer.targetEmail);setTransfer({...transfer,targetEmail:''});await load();setMessage('Convite enviado. A troca só ocorrerá após o destinatário entrar com código e aceitar.');}catch(error){setMessage(error instanceof Error?error.message:'Falha ao iniciar transferência.');}finally{setWorking('');}};
  const profileFields:Array<[keyof InstallationProfile,string]>=[['portalName','Nome do portal'],['institutionName','Instituição'],['institutionAcronym','Sigla da instituição'],['courseName','Curso'],['courseAcronym','Sigla do curso'],['departmentName','Unidade/departamento'],['campusName','Campus'],['city','Cidade/UF'],['protocolPrefix','Prefixo do protocolo'],['driveRootFolderName','Nome da pasta raiz no Drive'],['defaultInstitutionName','Instituição interna padrão'],['defaultDefenseLocation','Local padrão da defesa']];
  return <div className="space-y-4">
    <section className={card}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black text-slate-950">Identidade da instalação</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-600">Esta é a fonte única da instituição e do curso. Ao replicar o software, o novo Master troca estes dados sem editar código.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase text-emerald-800">uma instalação · um curso</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{profileFields.map(([key,label])=><label key={key} className="text-xs font-bold text-slate-700">{label}<input value={String(profile[key]||'')} onChange={event=>setProfile(current=>({...current,[key]:event.target.value}))} className={`${fieldClass} mt-1`}/></label>)}<label className="text-xs font-bold text-slate-700">Domínios dos alunos<input value={profile.studentEmailDomains.join(', ')} onChange={event=>setProfile(current=>({...current,studentEmailDomains:event.target.value.split(',').map(value=>value.trim())}))} className={`${fieldClass} mt-1`} placeholder="edu.instituicao.br"/></label><label className="text-xs font-bold text-slate-700">Domínios internos<input value={profile.internalEmailDomains.join(', ')} onChange={event=>setProfile(current=>({...current,internalEmailDomains:event.target.value.split(',').map(value=>value.trim())}))} className={`${fieldClass} mt-1`} placeholder="instituicao.br"/></label></div><button type="button" onClick={saveProfile} disabled={working==='profile'} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-xs font-black text-white disabled:opacity-50">{working==='profile'?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Publicar identidade</button></section>
    <div className="grid gap-4 xl:grid-cols-2">
      <section className={card}><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-blue-700"/><h3 className="font-black">Períodos e editais</h3></div><p className="mt-1 text-xs text-slate-600">Organiza inscrições, defesas e numeração por período.</p><form onSubmit={createCycle} className="mt-3 grid gap-2 sm:grid-cols-2"><input required value={newCycle.label} onChange={event=>setNewCycle(current=>({...current,label:event.target.value}))} placeholder="Ex.: 2027/1" className={fieldClass}/><div className="grid grid-cols-2 gap-2"><input required type="number" value={newCycle.year} onChange={event=>setNewCycle(current=>({...current,year:Number(event.target.value)}))} className={fieldClass}/><input required value={newCycle.term} onChange={event=>setNewCycle(current=>({...current,term:event.target.value}))} placeholder="Semestre" className={fieldClass}/></div>{[['submissionOpenAt','Início das inscrições'],['submissionCloseAt','Fim das inscrições'],['defenseStartAt','Início das defesas'],['defenseEndAt','Fim das defesas']].map(([key,label])=><label key={key} className="text-[11px] font-bold text-slate-600">{label}<input required type="datetime-local" value={(newCycle as any)[key]} onChange={event=>setNewCycle(current=>({...current,[key]:event.target.value}))} className={`${fieldClass} mt-1`}/></label>)}<button disabled={working==='cycle'} className="rounded-xl bg-slate-900 px-3 py-2.5 text-xs font-black text-white sm:col-span-2">Criar período em rascunho</button></form><div className="mt-3 space-y-2">{cycles.map(cycle=><div key={cycle.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border bg-slate-50 p-3"><div><strong className="text-sm">{cycle.label}</strong><p className="text-[11px] text-slate-500">{cycle.status} · {cycle.year}/{cycle.term}</p></div><div className="flex gap-1">{cycle.status!=='OPEN'&&<button type="button" onClick={()=>void setCycleStatus(cycle,'OPEN')} className="rounded-lg border bg-white px-2 py-1.5 text-[10px] font-black">Abrir</button>}{cycle.status==='OPEN'&&<button type="button" onClick={()=>void setCycleStatus(cycle,'CLOSED')} className="rounded-lg border bg-white px-2 py-1.5 text-[10px] font-black">Encerrar</button>}<button type="button" onClick={()=>void setCycleStatus(cycle,'ARCHIVED')} className="rounded-lg border bg-white px-2 py-1.5 text-[10px] font-black">Arquivar</button></div></div>)}</div></section>
      <section className={card}><div className="flex items-center gap-2"><Flag className="h-5 w-5 text-purple-700"/><h3 className="font-black">Funcionalidades e implantação gradual</h3></div><p className="mt-1 text-xs text-slate-600">Desative módulos novos sem remover dados ou alterar código.</p><div className="mt-3 space-y-2">{flags.map(flag=><label key={flag.key} className="flex cursor-pointer items-center justify-between gap-3 rounded-xl border p-3"><span><strong className="block text-xs">{flag.description}</strong><span className="text-[10px] text-slate-500">{flag.key}</span></span><input type="checkbox" checked={flag.enabled} disabled={working===flag.key} onChange={()=>void toggleFlag(flag)} className="h-5 w-5 accent-emerald-700"/></label>)}</div></section>
      <section className={card}><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-amber-700"/><h3 className="font-black">Transferência institucional</h3></div><p className="mt-1 text-xs leading-5 text-slate-600">A troca usa duas etapas: solicitação por administrador autenticado e aceite pelo novo titular após código por e-mail.</p><form onSubmit={startTransfer} className="mt-3 grid gap-2 sm:grid-cols-[0.8fr_1.2fr_auto]"><select value={transfer.role} onChange={event=>setTransfer(current=>({...current,role:event.target.value as any}))} className={fieldClass}><option value="COMMISSION_PRESIDENT">Presidência</option><option value="MASTER_ADMIN">Usuário Master</option></select><input required type="email" value={transfer.targetEmail} onChange={event=>setTransfer(current=>({...current,targetEmail:event.target.value}))} placeholder="novo.titular@instituicao.br" className={fieldClass}/><button disabled={working==='transfer'} className="rounded-xl bg-amber-700 px-3 py-2 text-xs font-black text-white">Enviar convite</button></form><div className="mt-3 space-y-2">{transfers.slice(0,5).map(item=><div key={item.id} className="rounded-xl border bg-slate-50 p-3 text-xs"><strong>{item.role==='MASTER_ADMIN'?'Master':'Presidente'} · {item.status}</strong><p className="mt-1 text-slate-500">Destino {item.targetEmail} · expira {new Date(item.expiresAt).toLocaleString('pt-BR')}</p></div>)}</div></section>
      <section className={card}><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-emerald-700"/><h3 className="font-black">Indicadores operacionais</h3></div><p className="mt-1 text-xs text-slate-600">Somente agregados, sem nomes, e-mails, matrículas ou títulos.</p>{metrics?<div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{[['TCCs',metrics.processes.total],['Concluídos',metrics.processes.completed],['Conclusão',`${metrics.processes.completionRate}%`],['Publicação',`${metrics.publication.rate}%`],['Asten concluído',metrics.signatures.archived],['E-mails aceitos',metrics.emails.accepted]].map(([label,value])=><div key={String(label)} className="rounded-xl border bg-slate-50 p-3"><span className="text-[10px] font-black uppercase text-slate-500">{label}</span><strong className="mt-1 block text-xl text-slate-950">{value}</strong></div>)}</div>:<p className="mt-4 text-xs text-slate-500">Indicadores indisponíveis ou módulo desativado.</p>}</section>
    </div>
    {message&&<div role="status" className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-semibold text-emerald-950"><CheckCircle2 className="h-4 w-4"/>{message}</div>}
  </div>;
};
