import React, { useMemo, useState } from 'react';
import type { IntegrationStudioSettings } from '../types/integrationStudio';
import type { OperationalConfig } from '../types/operationalConfig';
import type { StageDeadline, WaitingMilestone } from '../types/workflowOperations';
import { workflowPolicy } from '../utils/workflowOperations';
import { registrationQuestions } from '../utils/operationalConfig';
import { apiClient } from '../services/apiClient';

const milestones:Record<WaitingMilestone,string>={LOCATION:'Confirmação do local',EVALUATION:'Avaliação da defesa',ATA:'Assinatura da Ata',FINAL_DELIVERY:'Entrega final',TERM:'Assinatura do Termo',DECLARATION:'Assinatura da Declaração'};
const changes:Record<string,string>={ADDED:'Incluído',REMOVED:'Removido',CHANGED:'Alterado'};
export function WorkflowWorkbenchPanel({ studio, config, onChange }:{studio:IntegrationStudioSettings;config:OperationalConfig;onChange:(config:OperationalConfig)=>void}){
  const policy=workflowPolicy({...studio,operationalConfig:config});
  const [type,setType]=useState('CONVITE');
  const [samples,setSamples]=useState<Record<string,string>>({TITULO:'Trabalho fictício para conferência do modelo',ALUNO_1_NOME:'Ana Maria de Demonstração',DEFESA_DATA_HORA:'2026-10-20T14:30'});
  const [sampleKey,setSampleKey]=useState('ALUNO_1_MATRICULA');
  const [preview,setPreview]=useState<any>(null);
  const [comparison,setComparison]=useState<any>(null);
  const [working,setWorking]=useState('');
  const [message,setMessage]=useState('');
  const sampleFields=useMemo(()=>[...registrationQuestions(studio),...(studio.formTemplates||[]).flatMap((form:any)=>(form.questions||[]).map((field:any)=>({fieldKey:String(field.fieldKey||''),label:String(field.label||field.fieldKey||''),fieldType:field.fieldType||'text'}))),...(studio.matrixColumns||[]).map((field:any)=>({fieldKey:String(field.id||field.name||''),label:String(field.name||field.id||''),fieldType:'text'}))].filter((field,index,all)=>field.fieldKey&&all.findIndex(other=>other.fieldKey===field.fieldKey)===index),[studio.formTemplates,studio.matrixColumns,studio.revision]);
  const update=(patch:Partial<typeof policy>)=>onChange({...config,workflow:{...policy,...patch}});
  const deadline=(id:string,patch:Partial<StageDeadline>)=>update({deadlines:policy.deadlines.map(rule=>rule.id===id?{...rule,...patch}:rule)});
  const run=async(kind:'preview'|'compare')=>{setWorking(kind);setMessage('');try{if(kind==='preview'){setPreview(null);setPreview(await apiClient.previewOfficialModel(type,{...studio,operationalConfig:config},samples));}else setComparison(await apiClient.compareStudioDraft({...studio,operationalConfig:config}));}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível concluir a conferência.');}finally{setWorking('');}};
  const download=()=>{
    if(!preview)return;const a=document.createElement('a');a.download=preview.fileName;
    if(preview.downloadUrl){a.href=preview.downloadUrl;a.rel='noreferrer';a.click();return;}
    const bytes=Uint8Array.from(atob(preview.contentBase64),(char)=>char.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));a.href=url;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  };
  return <div className="space-y-5">
    <details className="portal-card p-5"><summary className="cursor-pointer text-lg font-semibold">7. Conferir o PDF real do modelo</summary>
      <p className="my-3">Após cadastrar o DOCX do Master, gere uma amostra usando a conversão do Google. Confira o documento preenchido antes de publicar o fluxo. A amostra recebe marca d’água e não é enviada à banca ou à Asten.</p>
      <label className="block">Modelo<select className="portal-input mt-1" value={type} onChange={e=>{setType(e.target.value);setPreview(null);}}>{[['CONVITE','Convite'],['ATA','Ata'],['TERMO','Termo de autorização'],['DECLARACAO','Declaração da banca']].map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
      <fieldset className="mt-4 grid gap-4 sm:grid-cols-2"><legend className="font-semibold">Valores fictícios para conferir o preenchimento</legend>{Object.entries(samples).map(([key,value])=><label key={key}>{sampleFields.find(field=>field.fieldKey===key)?.label||key}<input className="portal-input mt-1" value={value} maxLength={10000} onChange={e=>{setSamples({...samples,[key]:e.target.value});setPreview(null);}}/></label>)}</fieldset>
      <div className="my-4 flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1">Adicionar um campo à amostra<select className="portal-input mt-1" value={sampleKey} onChange={e=>setSampleKey(e.target.value)}>{sampleFields.filter(field=>!(field.fieldKey in samples)).map(field=><option key={field.fieldKey} value={field.fieldKey}>{field.label}</option>)}</select></label><button className="portal-action" type="button" onClick={()=>{if(sampleKey&&!Object.hasOwn(samples,sampleKey))setSamples({...samples,[sampleKey]:''});}}>Adicionar campo</button></div>
      <button type="button" className="portal-action portal-action-primary" disabled={Boolean(working)} onClick={()=>void run('preview')}>{working==='preview'?'Gerando e analisando o PDF…':'Gerar amostra no Google'}</button>
      {preview&&<div className="mt-4 space-y-3"><p role="status">{preview.analysis.pages} página(s) gerada(s). {preview.analysis.issues.length?'Confira os apontamentos abaixo.':'Nenhum problema detectado pela análise automática.'} A conferência visual do PDF continua necessária.</p>{preview.analysis.issues.length>0&&<ul className="list-disc space-y-2 pl-5">{preview.analysis.issues.map((issue:any,i:number)=><li key={i}>{issue.page?`Página ${issue.page}: `:''}{issue.message}</li>)}</ul>}<button type="button" className="portal-action" onClick={download}>Baixar amostra sem validade</button>{preview.expiresAt&&<p className="text-sm">O link expira em um minuto. Gere novamente se necessário.</p>}<p className="break-all text-sm">Versão do modelo conferida: {preview.templateSha256?.slice(0,16)}…</p></div>}
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><label>Reserva inferior para assinatura (pontos)<input type="number" min={0} max={300} className="portal-input" value={policy.documentLayout.signatureReservePoints} onChange={e=>update({documentLayout:{...policy.documentLayout,signatureReservePoints:Number(e.target.value)}})}/></label><label>Limite de páginas do documento<input type="number" min={1} max={60} className="portal-input" value={policy.documentLayout.maximumPages} onChange={e=>update({documentLayout:{...policy.documentLayout,maximumPages:Number(e.target.value)}})}/></label></div>
    </details>
    <details className="portal-card p-5"><summary className="cursor-pointer text-lg font-semibold">8. Comparar com o fluxo publicado</summary><p className="my-3">Veja o que mudou em formulários, modelos, e-mails, etapas e aparência antes de publicar.</p><button type="button" className="portal-action" disabled={Boolean(working)} onClick={()=>void run('compare')}>Conferir alterações do rascunho</button>
      {comparison&&<div className="mt-4 space-y-3"><p>{comparison.activeProcesses} TCC(s) em andamento. {comparison.notice}</p><p>{comparison.changes.length} alteração(ões) em relação à revisão {comparison.baseRevision}.</p><div className="overflow-x-auto"><table className="portal-data-table"><caption className="sr-only">Alterações em relação à versão publicada</caption><thead><tr><th scope="col">Área</th><th scope="col">Alteração</th><th scope="col">Detalhe</th></tr></thead><tbody>{comparison.changes.map((item:any)=><tr key={item.key}><th scope="row">{item.area}</th><td>{changes[item.change]}</td><td className="break-words">{item.key}: {item.detail}</td></tr>)}</tbody></table></div></div>}
    </details>
    <details className="portal-card p-5"><summary className="cursor-pointer text-lg font-semibold">9. Prazos, lembretes e conferência do cadastro</summary><p className="my-3">Os prazos contam dias úteis a partir da entrada na etapa. Na avaliação, a contagem começa na data agendada da defesa. A rotina diária envia apenas lembretes publicados, com os destinatários do modelo escolhido.</p>
      <div className="grid gap-4 sm:grid-cols-3"><label>Validade do rascunho (dias)<input type="number" min={1} max={180} className="portal-input" value={policy.draftExpiryDays} onChange={e=>update({draftExpiryDays:Number(e.target.value)})}/></label><label>Mínimo de caracteres da matrícula<input type="number" min={1} max={30} className="portal-input" value={policy.identity.minimumStudentIdLength} onChange={e=>update({identity:{...policy.identity,minimumStudentIdLength:Number(e.target.value)}})}/></label><label>Quantidade de dígitos do SIAPE<input type="number" min={1} max={20} className="portal-input" value={policy.identity.siapeLength} onChange={e=>update({identity:{...policy.identity,siapeLength:Number(e.target.value)}})}/></label></div>
      <fieldset className="my-4 flex flex-wrap gap-4"><legend className="mb-2 font-semibold">Dias úteis</legend>{['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'].map((day,i)=><label className="flex items-center gap-2" key={day}><input type="checkbox" checked={policy.weekdays.includes(i)} onChange={e=>update({weekdays:e.target.checked?[...policy.weekdays,i]:policy.weekdays.filter(value=>value!==i)})}/>{day}</label>)}</fieldset>
      <label className="block">Feriados e recessos (uma data AAAA-MM-DD por linha)<textarea rows={4} className="portal-input mt-1" value={policy.holidays.join('\n')} onChange={e=>update({holidays:e.target.value.split('\n')})} onBlur={()=>update({holidays:policy.holidays.map(day=>day.trim()).filter(Boolean)})}/></label>
      <div className="mt-4 space-y-4">{policy.deadlines.map(rule=><article key={rule.id} className="portal-card grid gap-4 p-4 sm:grid-cols-2 lg:grid-cols-3"><label>Etapa<select className="portal-input" value={rule.milestone} onChange={e=>deadline(rule.id,{milestone:e.target.value as WaitingMilestone})}>{Object.entries(milestones).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Prazo em dias úteis<input type="number" min={0} max={365} className="portal-input" value={rule.businessDays} onChange={e=>deadline(rule.id,{businessDays:Number(e.target.value)})}/></label><label>Modelo do lembrete<select className="portal-input" value={rule.emailTemplateId} onChange={e=>deadline(rule.id,{emailTemplateId:e.target.value})}><option value="">Selecione um e-mail sem anexos</option>{studio.emailTemplates.filter(mail=>!Array.isArray(mail.attachments)||!mail.attachments.length).map(mail=><option key={String(mail.id)} value={String(mail.id)}>{String(mail.name||mail.id)}</option>)}</select></label><label>Intervalo entre lembretes (dias úteis)<input className="portal-input" type="number" min={1} max={365} value={rule.reminderEveryDays} onChange={e=>deadline(rule.id,{reminderEveryDays:Number(e.target.value)})}/></label><label>Máximo de lembretes por destinatário<input className="portal-input" type="number" min={1} max={10} value={rule.maxReminders} onChange={e=>deadline(rule.id,{maxReminders:Number(e.target.value)})}/></label><label className="flex items-center gap-2"><input type="checkbox" checked={rule.active} onChange={e=>deadline(rule.id,{active:e.target.checked})}/>Ativar após publicar</label><button type="button" className="portal-action" onClick={()=>update({deadlines:policy.deadlines.filter(item=>item.id!==rule.id)})}>Remover regra</button></article>)}</div>
      <button type="button" className="portal-action mt-4" disabled={policy.deadlines.length>=20} onClick={()=>update({deadlines:[...policy.deadlines,{id:crypto.randomUUID(),milestone:'LOCATION',businessDays:3,reminderEveryDays:2,maxReminders:3,emailTemplateId:'',active:false}]})}>Adicionar prazo e lembrete</button>
      <p className="mt-3 text-sm">No texto do e-mail, use PRAZO_ETAPA e DATA_LIMITE junto das variáveis do TCC. A formatação da data é definida em “Formatação dos marcadores”. Confira os destinatários na aba E-mails.</p>
    </details>
    {message&&<p role="alert" className="portal-card p-4">{message}</p>}
  </div>;
}
