import { portalConfirm } from '../services/portalDialogs';
import React, { useCallback, useEffect, useState } from 'react';
import { apiClient } from '../services/apiClient';
export function WorkflowRecoveryPanel(){
  const [data,setData]=useState<any>(null),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
  const load=useCallback(async()=>{setBusy('load');try{setData(await apiClient.getWorkflowOperations());}catch(e){setMessage(e instanceof Error?e.message:'Não foi possível consultar o andamento.');}finally{setBusy('');}},[]);
  useEffect(()=>{void load();},[load]);
  const retry=async(path:string)=>{
    const warning=path.includes('/reminders/')?'Confira no Gmail se este lembrete já foi entregue. Confirmar uma nova tentativa?':`Retomar usando a revisão ${data.studioRevision} publicada? As ações já concluídas serão preservadas.`;
    if(!(await portalConfirm(warning)))return;setBusy(path);setMessage('');
    try{await apiClient.retryWorkflowOperation(path,data.studioRevision);await load();setMessage('Tentativa registrada. Confira o estado atualizado abaixo.');}catch(e){setMessage(e instanceof Error?e.message:'Falha na retomada.');}finally{setBusy('');}
  };
  const maintain=async()=>{setBusy('maintenance');setMessage('');try{const result=await apiClient.runWorkflowMaintenance();await load();setMessage(`${result.sent} lembrete(s) aceito(s) pelo Gmail; ${result.failed} com falha. ${result.configurationErrors.join(' ')}${result.deferred?' Há envios restantes para a próxima execução.':''}`);}catch(e){setMessage(e instanceof Error?e.message:'Rotina indisponível.');}finally{setBusy('');}};
  return <section className="portal-card space-y-4 p-5" aria-labelledby="workflow-recovery-title">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 id="workflow-recovery-title" className="text-lg font-bold">Central de andamento e retomada</h3><p className="mt-1">Acompanhe o que impede cada TCC de avançar e preserve os documentos e envios já concluídos.</p></div><button type="button" className="portal-action" disabled={Boolean(busy)} onClick={()=>void load()}>Atualizar andamento</button></div>
    {message&&<p role="status" className="rounded-lg border p-3">{message}</p>}
    {data&&<><p>{data.queueTotal} pendência(s) de fluxo, documentos ou arquivamento. {data.deadlineOverdueTotal} prazo(s) vencido(s).{data.queueTotal>data.queue.length||data.deadlineTotal>data.deadlines.length?' A tela mostra os 500 primeiros registros; use os filtros dos TCCs para investigar o restante.':''}</p>
      {data.planningError&&<p role="alert" className="rounded-lg border border-amber-500 bg-amber-50 p-3 text-amber-950">Os prazos publicados estão incoerentes: {data.planningError} Corrija e publique novamente o Estúdio antes de executar lembretes.</p>}
      <div className="grid gap-3 lg:grid-cols-2">{data.queue.map((item:any)=><article key={`${item.kind}:${item.id}`} className="portal-card space-y-3 p-4"><h4 className="font-bold">{item.protocol} · {item.title}</h4><p>{item.reason}</p>{item.completedActions.length>0&&<p className="text-sm">Já preservado: {item.completedActions.join('; ')}.</p>}{item.retryPath?<button className="portal-action" disabled={Boolean(busy)} type="button" onClick={()=>void retry(item.retryPath)}>{item.actionLabel}</button>:<p className="text-sm">Confira o envelope na Asten e registre a reconciliação na Central de Integrações.</p>}</article>)}</div>
      <details className="rounded-lg border p-4"><summary className="cursor-pointer font-semibold">Prazos e lembretes publicados</summary><div className="mt-3 overflow-x-auto"><table className="portal-data-table"><caption className="sr-only">Prazos por TCC</caption><thead><tr><th scope="col">TCC</th><th scope="col">Etapa</th><th scope="col">Data limite</th><th scope="col">Situação</th></tr></thead><tbody>{data.deadlines.map((item:any)=><tr key={`${item.processId}:${item.rule.id}`}><th scope="row">{item.protocol}</th><td>{item.label}</td><td>{item.dueDate.split('-').reverse().join('/')}</td><td>{item.overdue?'Prazo vencido':'No prazo'}</td></tr>)}</tbody></table></div><button type="button" className="portal-action mt-4" disabled={Boolean(busy)} onClick={()=>void maintain()}>Executar lembretes vencidos</button><p className="mt-2 text-sm">Usa as regras publicadas e o mesmo limite da rotina diária.</p></details>
      <details className="rounded-lg border p-4"><summary className="cursor-pointer font-semibold">Histórico de lembretes (últimos 200)</summary><ul className="mt-3 space-y-3">{data.reminders.map((item:any)=><li className="rounded-lg border p-3" key={item.id}><p className="break-words">{item.recipient} · prazo {item.dueDate} · tentativa {item.ordinal}: {item.status==='SENT'?'Aceito pelo Gmail':item.status==='FAILED'?'Falha de envio':'Resultado ainda não confirmado'}</p>{item.error&&<p>{item.error}</p>}{item.status==='FAILED'&&<button type="button" className="portal-action mt-2" disabled={Boolean(busy)} onClick={()=>void retry(`/api/admin/workflow/reminders/${item.id}/retry`)}>Revisar e tentar novamente</button>}</li>)}</ul></details>
    </>}
  </section>;
}
